# Generated by Django 5.2.6 on 2025-09-09 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=50, null=True)),
                ('gender_identity', models.CharField(blank=True, max_length=100, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=10, null=True)),
                ('height_cm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('waist_cm', models.FloatField(blank=True, null=True)),
                ('hip_cm', models.FloatField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=64, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('occupation', models.CharField(blank=True, max_length=150, null=True)),
                ('smoking_status', models.CharField(blank=True, max_length=100, null=True)),
                ('alcohol_use', models.CharField(blank=True, max_length=100, null=True)),
                ('physical_activity_level', models.CharField(blank=True, max_length=100, null=True)),
                ('diet_type', models.CharField(blank=True, max_length=100, null=True)),
                ('sleep_hours', models.FloatField(blank=True, null=True)),
                ('stress_level', models.CharField(blank=True, max_length=100, null=True)),
                ('chronic_conditions', models.JSONField(blank=True, null=True)),
                ('surgeries', models.JSONField(blank=True, null=True)),
                ('allergies', models.JSONField(blank=True, null=True)),
                ('medications_current', models.JSONField(blank=True, null=True)),
                ('family_history', models.JSONField(blank=True, null=True)),
                ('vaccinations', models.JSONField(blank=True, null=True)),
                ('reproductive_health_notes', models.TextField(blank=True, null=True)),
                ('primary_physician_name', models.CharField(blank=True, max_length=150, null=True)),
                ('primary_physician_contact', models.CharField(blank=True, max_length=150, null=True)),
                ('insurance_provider', models.CharField(blank=True, max_length=150, null=True)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=150, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150, null=True)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=64, null=True)),
                ('preferred_hospital', models.CharField(blank=True, max_length=150, null=True)),
                ('communication_preferences', models.JSONField(blank=True, null=True)),
                ('language_preferences', models.JSONField(blank=True, null=True)),
                ('data_sharing_consent', models.BooleanField(default=False)),
                ('research_consent', models.BooleanField(default=False)),
                ('dna_profile_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
