# Generated by Django 5.2.6 on 2025-09-10 03:26

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile image (max 5MB, formats: JPG, PNG, GIF)', null=True, upload_to=authentication.models.user_profile_image_path, validators=[authentication.models.validate_image_size]),
        ),
    ]
