"""
Django settings for aevum project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialise environment variables
env = environ.Env(
    DEBUG=(bool, True),
)
# Read .env file located in the project root (code directory)
environ.Env.read_env(str(BASE_DIR / '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='replace-me-in-.env')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])

# Add 'testserver' to ALLOWED_HOSTS for testing
if 'testserver' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('testserver')

# Add Android emulator host if not already present
if '10.0.2.2' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('10.0.2.2')

# AI / LLM SETTINGS
GROQ_API_KEY = env('GROQ_API_KEY', default='')
GROQ_MODEL = env('GROQ_MODEL', default='')

# AI Companion Settings
AI_COMPANION_ENABLE_SUMMARIZATION = env.bool('AI_COMPANION_ENABLE_SUMMARIZATION', default=True)
AI_COMPANION_MAX_SUMMARY_WORDS = env.int('AI_COMPANION_MAX_SUMMARY_WORDS', default=150)

# RAG (Retrieval-Augmented Generation) Settings
RAG_EMBEDDING_MODEL = env('RAG_EMBEDDING_MODEL', default='sentence-transformers/all-MiniLM-L6-v2')
RAG_CHROMA_PERSIST_DIR = env('RAG_CHROMA_PERSIST_DIR', default=str(BASE_DIR / 'chroma_db'))
RAG_COLLECTION_NAME = env('RAG_COLLECTION_NAME', default='mental_health_knowledge_base')
RAG_CHUNK_SIZE = env.int('RAG_CHUNK_SIZE', default=500)
RAG_CHUNK_OVERLAP = env.int('RAG_CHUNK_OVERLAP', default=50)
RAG_TOP_K_RESULTS = env.int('RAG_TOP_K_RESULTS', default=3)
RAG_ENABLED = env.bool('RAG_ENABLED', default=True)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'django_filters',
    # Local apps
    'authentication',
    'mental_wellness',
    'nutrition',
    'healthcare',
    'dna_profile',
    'ai_companion',
    'dashboard',
    'smart_journal',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'aevum.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aevum.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': env('DB_ENGINE', default='django.db.backends.sqlite3'),
        'NAME': env('DB_NAME', default=str(BASE_DIR / 'db.sqlite3')),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Media files (User uploaded files)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Email Settings
EMAIL_BACKEND = env('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = env('EMAIL_HOST', default='')
EMAIL_PORT = env.int('EMAIL_PORT', default=587)
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=True)
EMAIL_USE_SSL = env.bool('EMAIL_USE_SSL', default=False)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER)
CONTACT_EMAIL = env('CONTACT_EMAIL', default=EMAIL_HOST_USER)
ADMIN_EMAIL = env('ADMIN_EMAIL', default=EMAIL_HOST_USER)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Pagination
ITEMS_PER_PAGE = env.int('ITEMS_PER_PAGE', default=15)

# Logging
LOG_LEVEL = env('LOG_LEVEL', default='INFO')

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
    },
    'loggers': {
        'ai_companion': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# SEO & Analytics
GOOGLE_ANALYTICS_ID = env('GOOGLE_ANALYTICS_ID', default='')
SITE_URL = env('SITE_URL', default='')
SITEMAP_URL = env('SITEMAP_URL', default='')

# DRF configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'aevum.pagination.StandardResultsPagination',
}

# JWT SETTINGS
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=env.int('ACCESS_TOKEN_LIFETIME_MINUTES', default=60)),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=env.int('REFRESH_TOKEN_LIFETIME_DAYS', default=1)),
    'BLACKLIST_AFTER_ROTATION': True,
}

# drf-spectacular configuration
SPECTACULAR_SETTINGS = {
    'TITLE': 'Aevum Health API',
    'DESCRIPTION': 'APIs for authentication, mental wellness, nutrition, healthcare, DNA profile, AI companion, and dashboard.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/',
    'AUTHENTICATION_EXTENSION': 'drf_spectacular.extensions.auth.CustomAuthenticationExtension',
    'SECURITY': [
        {
            'type': 'http',
            'scheme': 'bearer',
            'bearerFormat': 'JWT',
            'description': 'JWT token obtained from /api/authentication/login/ endpoint'
        }
    ],
    'TAGS': [
        {'name': 'Authentication', 'description': 'User authentication and profile management'},
        {'name': 'Mental Wellness', 'description': 'Mental health and wellness features'},
        {'name': 'Nutrition', 'description': 'Nutrition tracking and management'},
        {'name': 'Healthcare', 'description': 'Healthcare management features'},
        {'name': 'DNA Profile', 'description': 'DNA and genetic profiling'},
        {'name': 'AI Companion', 'description': 'AI assistant features'},
        {'name': 'Dashboard', 'description': 'Dashboard analytics, early access requests, and contact form management'},
        {'name': 'Smart Journal', 'description': 'Personal journaling system with AI insights and analytics'},
    ],
}
