# Generated by Django 5.2.6 on 2025-09-13 04:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import smart_journal.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('PERSONAL', 'Personal Life'), ('WORK', 'Work & Career'), ('HEALTH', 'Health & Wellness'), ('RELATIONSHIPS', 'Relationships'), ('GOALS', 'Goals & Achievements'), ('TRAVEL', 'Travel & Adventures'), ('LEARNING', 'Learning & Education'), ('CREATIVITY', 'Creative Projects'), ('FINANCE', 'Finance & Money'), ('GRATITUDE', 'Gratitude & Reflection'), ('DREAMS', 'Dreams & Aspirations'), ('DAILY', 'Daily Life'), ('CUSTOM', 'Custom Category')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('color_hex', models.CharField(default='#6366f1', help_text='Hex color code for UI display (e.g., #FF5733)', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Icon name or emoji for category', max_length=50, null=True)),
                ('is_system_category', models.BooleanField(default=False, help_text='Whether this is a system-wide category or user-specific')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who created this category (null for system categories)', on_delete=django.db.models.deletion.CASCADE, related_name='journal_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Category',
                'verbose_name_plural': 'Journal Categories',
                'ordering': ['category_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(help_text='Title of the journal entry', max_length=200)),
                ('content', models.TextField(help_text='Main content of the journal entry')),
                ('entry_date', models.DateField(default=django.utils.timezone.now, help_text='Date this entry represents (can be different from created_at)')),
                ('mood_rating', models.PositiveIntegerField(blank=True, choices=[(1, '😞 Very Sad'), (2, '😕 Sad'), (3, '😐 Neutral'), (4, '😊 Happy'), (5, '😄 Very Happy')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('energy_level', models.PositiveIntegerField(blank=True, choices=[(1, '🔋 Very Low'), (2, '🔋 Low'), (3, '🔋 Moderate'), (4, '🔋 High'), (5, '🔋 Very High')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('structured_data', models.JSONField(blank=True, default=dict, help_text='Structured data based on template or custom fields')),
                ('location', models.CharField(blank=True, help_text='Location where this entry was written', max_length=200, null=True)),
                ('weather', models.CharField(blank=True, help_text='Weather conditions', max_length=100, null=True)),
                ('privacy_level', models.CharField(choices=[('PRIVATE', 'Private (Only Me)'), ('SHARED', 'Shared (Selected People)'), ('PUBLIC', 'Public (Anyone)')], default='PRIVATE', max_length=10)),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=False)),
                ('ai_insights', models.JSONField(blank=True, default=dict, help_text='AI-generated insights and analysis')),
                ('sentiment_score', models.FloatField(blank=True, help_text='AI-calculated sentiment score (-1 to 1)', null=True, validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('estimated_reading_time', models.PositiveIntegerField(default=0, help_text='Estimated reading time in minutes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='smart_journal.journalcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=smart_journal.models.journal_attachment_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'pdf', 'doc', 'docx', 'txt', 'mp3', 'wav', 'mp4', 'mov'])])),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(choices=[('IMAGE', 'Image'), ('DOCUMENT', 'Document'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('OTHER', 'Other')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='smart_journal.journalentry')),
            ],
            options={
                'verbose_name': 'Journal Attachment',
                'verbose_name_plural': 'Journal Attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('MOOD_PATTERN', 'Mood Pattern'), ('WORD_FREQUENCY', 'Word Frequency'), ('TOPIC_ANALYSIS', 'Topic Analysis'), ('SENTIMENT_TREND', 'Sentiment Trend'), ('WRITING_STYLE', 'Writing Style'), ('TIME_PATTERN', 'Time Pattern'), ('CATEGORY_ANALYSIS', 'Category Analysis'), ('GOAL_PROGRESS', 'Goal Progress')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('insight_data', models.JSONField(default=dict, help_text='Structured data for the insight')),
                ('confidence_score', models.FloatField(help_text='AI confidence score for this insight', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('analysis_start_date', models.DateField()),
                ('analysis_end_date', models.DateField()),
                ('entries_analyzed', models.PositiveIntegerField(default=0)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('is_helpful', models.BooleanField(blank=True, null=True)),
                ('user_feedback', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Insight',
                'verbose_name_plural': 'Journal Insights',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField(help_text='Reminder message to show user')),
                ('reminder_type', models.CharField(choices=[('GENERAL', 'General Journaling'), ('GRATITUDE', 'Gratitude Practice'), ('REFLECTION', 'Daily Reflection'), ('GOAL_CHECK', 'Goal Check-in'), ('MOOD_CHECK', 'Mood Check'), ('CUSTOM', 'Custom Reminder')], max_length=15)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('CUSTOM', 'Custom')], max_length=10)),
                ('reminder_time', models.TimeField(help_text='Time of day to send reminder')),
                ('days_of_week', models.JSONField(default=list, help_text='Days of week for weekly reminders (0=Monday, 6=Sunday)')),
                ('is_active', models.BooleanField(default=True)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('next_reminder', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Reminder',
                'verbose_name_plural': 'Journal Reminders',
                'ordering': ['reminder_time'],
            },
        ),
        migrations.CreateModel(
            name='JournalStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('total_entries', models.PositiveIntegerField(default=0)),
                ('last_entry_date', models.DateField(blank=True, null=True)),
                ('milestones_achieved', models.JSONField(default=list, help_text='List of achieved milestones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal_streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Streak',
                'verbose_name_plural': 'Journal Streaks',
            },
        ),
        migrations.CreateModel(
            name='JournalTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color_hex', models.CharField(default='#6b7280', help_text='Hex color code for tag display', max_length=7)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_journal.journalentry')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_journal.journaltag')),
            ],
        ),
        migrations.AddField(
            model_name='journalentry',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='entries', through='smart_journal.JournalEntryTag', to='smart_journal.journaltag'),
        ),
        migrations.CreateModel(
            name='JournalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('template_type', models.CharField(choices=[('DAILY_REFLECTION', 'Daily Reflection'), ('GRATITUDE', 'Gratitude Journal'), ('GOAL_TRACKING', 'Goal Tracking'), ('MOOD_CHECK', 'Mood Check-in'), ('WORK_LOG', 'Work Log'), ('TRAVEL_LOG', 'Travel Log'), ('LEARNING_LOG', 'Learning Log'), ('HEALTH_LOG', 'Health Log'), ('RELATIONSHIP_LOG', 'Relationship Log'), ('CREATIVE_LOG', 'Creative Log'), ('CUSTOM', 'Custom Template')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('prompt_questions', models.JSONField(default=list, help_text='List of prompt questions for this template')),
                ('default_structure', models.JSONField(default=dict, help_text='Default structure/sections for entries using this template')),
                ('is_system_template', models.BooleanField(default=False, help_text='Whether this is a system-wide template')),
                ('is_public', models.BooleanField(default=False, help_text='Whether other users can use this template')),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who created this template (null for system templates)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Template',
                'verbose_name_plural': 'Journal Templates',
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template used for this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='smart_journal.journaltemplate'),
        ),
        migrations.AddIndex(
            model_name='journalcategory',
            index=models.Index(fields=['user', 'is_active'], name='smart_journ_user_id_668966_idx'),
        ),
        migrations.AddIndex(
            model_name='journalcategory',
            index=models.Index(fields=['category_type'], name='smart_journ_categor_3edf7f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journalcategory',
            unique_together={('name', 'user')},
        ),
        migrations.AddIndex(
            model_name='journalinsight',
            index=models.Index(fields=['user', 'insight_type'], name='smart_journ_user_id_5b3e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='journalinsight',
            index=models.Index(fields=['user', 'generated_at'], name='smart_journ_user_id_f28012_idx'),
        ),
        migrations.AddIndex(
            model_name='journalreminder',
            index=models.Index(fields=['user', 'is_active'], name='smart_journ_user_id_efc85b_idx'),
        ),
        migrations.AddIndex(
            model_name='journalreminder',
            index=models.Index(fields=['next_reminder'], name='smart_journ_next_re_472e58_idx'),
        ),
        migrations.AddIndex(
            model_name='journaltag',
            index=models.Index(fields=['user', 'name'], name='smart_journ_user_id_eb4302_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journaltag',
            unique_together={('name', 'user')},
        ),
        migrations.AddIndex(
            model_name='journalentrytag',
            index=models.Index(fields=['entry'], name='smart_journ_entry_i_da5e97_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentrytag',
            index=models.Index(fields=['tag'], name='smart_journ_tag_id_20c756_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journalentrytag',
            unique_together={('entry', 'tag')},
        ),
        migrations.AddIndex(
            model_name='journaltemplate',
            index=models.Index(fields=['user', 'is_active'], name='smart_journ_user_id_f0a056_idx'),
        ),
        migrations.AddIndex(
            model_name='journaltemplate',
            index=models.Index(fields=['template_type'], name='smart_journ_templat_e1f27f_idx'),
        ),
        migrations.AddIndex(
            model_name='journaltemplate',
            index=models.Index(fields=['is_system_template'], name='smart_journ_is_syst_da9ecb_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['user', 'entry_date'], name='smart_journ_user_id_5fa1da_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['user', 'category'], name='smart_journ_user_id_021e13_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['user', 'is_favorite'], name='smart_journ_user_id_a07170_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['user', 'is_archived'], name='smart_journ_user_id_2f7ff8_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['mood_rating'], name='smart_journ_mood_ra_951adb_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['energy_level'], name='smart_journ_energy__5fc44c_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['privacy_level'], name='smart_journ_privacy_2d9ab4_idx'),
        ),
    ]
