# Generated by Django 5.2.6 on 2025-09-16 13:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import dna_profile.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DNAKitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('ANCESTRY', 'Ancestry & Genealogy'), ('HEALTH', 'Health & Wellness'), ('FITNESS', 'Fitness & Nutrition'), ('COMPREHENSIVE', 'Comprehensive Analysis'), ('PHARMACOGENOMICS', 'Drug Response')], max_length=20)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('processing_time_days', models.PositiveIntegerField(default=21, help_text='Expected processing time in days')),
                ('features', models.JSONField(default=list, help_text='List of features included in this kit')),
                ('is_active', models.BooleanField(default=True)),
                ('requires_prescription', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DNAKitOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order_reference', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Order Pending'), ('CONFIRMED', 'Order Confirmed'), ('SHIPPED', 'Kit Shipped'), ('DELIVERED', 'Kit Delivered'), ('SAMPLE_RECEIVED', 'Sample Received at Lab'), ('PROCESSING', 'Sample Processing'), ('COMPLETED', 'Results Ready'), ('RESULTS_GENERATED', 'Results Generated'), ('CANCELLED', 'Order Cancelled'), ('FAILED', 'Processing Failed')], default='PENDING', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_method', models.CharField(choices=[('STANDARD', 'Standard Shipping (5-7 days)'), ('EXPRESS', 'Express Shipping (2-3 days)'), ('OVERNIGHT', 'Overnight Shipping (1 day)')], default='STANDARD', max_length=20)),
                ('shipping_address', models.JSONField(help_text='Complete shipping address')),
                ('tracking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('shipped_date', models.DateTimeField(blank=True, null=True)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('sample_received_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_completion_date', models.DateTimeField(blank=True, null=True)),
                ('payment_status', models.CharField(default='PENDING', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('lab_notes', models.TextField(blank=True, help_text='Internal lab notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dna_orders', to=settings.AUTH_USER_MODEL)),
                ('kit_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dna_profile.dnakittype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DNAKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit_id', models.CharField(help_text='Unique kit barcode/ID', max_length=50, unique=True)),
                ('is_activated', models.BooleanField(default=False)),
                ('activation_date', models.DateTimeField(blank=True, null=True)),
                ('sample_collected', models.BooleanField(default=False)),
                ('collection_date', models.DateTimeField(blank=True, null=True)),
                ('collection_method', models.CharField(blank=True, max_length=50, null=True)),
                ('sample_quality', models.CharField(blank=True, max_length=20, null=True)),
                ('quality_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kit', to='dna_profile.dnakitorder')),
            ],
        ),
        migrations.CreateModel(
            name='DNAPDFUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('pdf_file', models.FileField(help_text='DNA result PDF file', upload_to=dna_profile.models.dna_pdf_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('status', models.CharField(choices=[('UPLOADED', 'PDF Uploaded'), ('PROCESSING', 'Extracting Data'), ('COMPLETED', 'Processing Complete'), ('FAILED', 'Processing Failed'), ('MANUAL_REVIEW', 'Requires Manual Review')], default='UPLOADED', max_length=20)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True, help_text='Raw text extracted from PDF', null=True)),
                ('extraction_confidence', models.DecimalField(blank=True, decimal_places=2, help_text='Confidence score for extraction (0-100)', max_digits=5, null=True)),
                ('results_created_count', models.PositiveIntegerField(default=0, help_text='Number of DNA results created from this PDF')),
                ('processing_notes', models.TextField(blank=True, help_text='Processing notes and errors', null=True)),
                ('processed_by', models.CharField(blank=True, help_text='System or user who processed', max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_uploads', to='dna_profile.dnakit')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DNAResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.CharField(choices=[('ANCESTRY', 'Ancestry & Ethnicity'), ('HEALTH_RISK', 'Health Risk Factors'), ('CARRIER_STATUS', 'Carrier Status'), ('PHARMACOGENOMICS', 'Drug Response'), ('TRAITS', 'Physical Traits'), ('FITNESS', 'Fitness & Nutrition'), ('WELLNESS', 'Wellness Insights')], max_length=20)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('trait_name', models.CharField(max_length=200)),
                ('result_value', models.TextField(help_text='The actual result/finding')),
                ('confidence_level', models.CharField(choices=[('HIGH', 'High Confidence (>95%)'), ('MEDIUM', 'Medium Confidence (80-95%)'), ('LOW', 'Low Confidence (<80%)')], max_length=10)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, help_text='Risk score if applicable (0-100)', max_digits=5, null=True)),
                ('genetic_markers', models.JSONField(default=list, help_text='List of genetic markers analyzed')),
                ('methodology', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_population', models.CharField(blank=True, max_length=100, null=True)),
                ('clinical_significance', models.CharField(blank=True, max_length=20, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('requires_followup', models.BooleanField(default=False)),
                ('analysis_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_by', models.CharField(blank=True, help_text='Lab technician/geneticist', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='dna_profile.dnakit')),
            ],
            options={
                'ordering': ['category', 'trait_name'],
                'unique_together': {('kit', 'category', 'trait_name')},
            },
        ),
        migrations.CreateModel(
            name='ExtractedDNAData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait_name', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('result_value', models.TextField(blank=True, null=True)),
                ('confidence_level', models.CharField(blank=True, max_length=10, null=True)),
                ('risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('genetic_markers', models.JSONField(blank=True, default=list)),
                ('methodology', models.CharField(blank=True, max_length=100, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('extraction_confidence', models.DecimalField(blank=True, decimal_places=2, help_text='Confidence score for this specific extraction', max_digits=5, null=True)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('text_position', models.JSONField(blank=True, default=dict, help_text='Position in PDF where data was found')),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dna_result', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dna_profile.dnaresult')),
                ('pdf_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_data', to='dna_profile.dnapdfupload')),
            ],
            options={
                'ordering': ['page_number', 'trait_name'],
            },
        ),
        migrations.CreateModel(
            name='DNAConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_date', models.DateTimeField(null=True, blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consented', models.BooleanField(default=False)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('withdrawal_date', models.DateTimeField(null=True, blank=True)),
                ('consent_type', models.CharField(max_length=20, choices=[
                    ('ANALYSIS', 'DNA Analysis Consent'),
                    ('RESEARCH', 'Research Participation'),
                    ('DATA_SHARING', 'Data Sharing Consent'),
                    ('STORAGE', 'Sample Storage Consent'),
                    ('FAMILY_MATCHING', 'Family Matching Consent'),
                ])),
                ('consent_version', models.CharField(max_length=10, default='1.0')),
                ('ip_address', models.GenericIPAddressField(null=True, blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dna_consents', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(
                    null=True, 
                    blank=True, 
                    on_delete=django.db.models.deletion.CASCADE, 
                    related_name='consent', 
                    to='dna_profile.dnakitorder'
                )),
            ],
            options={
                'unique_together': {('user', 'consent_type')},
            },
        ),
        migrations.CreateModel(
            name='DNAReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('report_type', models.CharField(choices=[('PRELIMINARY', 'Preliminary Report'), ('COMPREHENSIVE', 'Comprehensive Report'), ('UPDATED', 'Updated Report'), ('CLINICAL', 'Clinical Report')], max_length=20)),
                ('status', models.CharField(choices=[('GENERATING', 'Report Generating'), ('READY', 'Report Ready'), ('DELIVERED', 'Report Delivered'), ('ARCHIVED', 'Report Archived')], default='GENERATING', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('summary', models.TextField(blank=True, null=True)),
                ('key_findings', models.JSONField(default=list)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('report_file_url', models.URLField(blank=True, help_text='URL to PDF report', null=True)),
                ('raw_data_url', models.URLField(blank=True, help_text='URL to raw genetic data', null=True)),
                ('quality_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('validated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('validation_date', models.DateTimeField(blank=True, null=True)),
                ('generated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='dna_profile.dnakit')),
            ],
            options={
                'ordering': ['-generated_date'],
                'unique_together': {('kit', 'report_type', 'version')},
            },
        ),
    ]
