# Generated by Django 5.2.6 on 2025-09-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dna_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnaconsent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
