# Generated by Django 5.2.6 on 2025-09-10 20:16

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('emotion_type', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral'), ('MIXED', 'Mixed')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('intensity_scale', models.CharField(default='1-10', help_text="Scale used to measure intensity (e.g., '1-10', '1-5')", max_length=20)),
                ('color_hex', models.CharField(help_text='Hex color code for UI display', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['emotion_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color_hex', models.CharField(help_text='Hex color code for UI display (e.g., #FF5733)', max_length=7)),
                ('icon', models.CharField(blank=True, help_text='Icon name or emoji', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Mood Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('EXERCISE', 'Exercise & Fitness'), ('SOCIAL', 'Social Activities'), ('WORK', 'Work & Career'), ('RELAXATION', 'Relaxation & Rest'), ('HOBBIES', 'Hobbies & Interests'), ('HEALTH', 'Health & Medical'), ('FAMILY', 'Family Time'), ('EDUCATION', 'Learning & Education'), ('SPIRITUAL', 'Spiritual & Meditation'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('typical_mood_impact', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative'), ('NEUTRAL', 'Neutral')], default='NEUTRAL', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('entry_date', models.DateField(default=datetime.date.today)),
                ('entry_time', models.TimeField(default=django.utils.timezone.now)),
                ('mood_level', models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Below Average'), (4, 'Average'), (5, 'Above Average'), (6, 'Good'), (7, 'Very Good'), (8, 'Great'), (9, 'Excellent'), (10, 'Outstanding')], help_text='Overall mood level (1-10 scale)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('energy_level', models.IntegerField(choices=[(1, 'Exhausted'), (2, 'Very Low'), (3, 'Low'), (4, 'Below Average'), (5, 'Average'), (6, 'Above Average'), (7, 'Good'), (8, 'High'), (9, 'Very High'), (10, 'Energetic')], help_text='Energy level (1-10 scale)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('anxiety_level', models.IntegerField(choices=[(1, 'No Anxiety'), (2, 'Very Low'), (3, 'Low'), (4, 'Mild'), (5, 'Moderate'), (6, 'Above Average'), (7, 'High'), (8, 'Very High'), (9, 'Severe'), (10, 'Extreme')], help_text='Anxiety level (1-10 scale)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('stress_level', models.IntegerField(blank=True, help_text='Stress level (1-10 scale)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('sleep_quality', models.IntegerField(blank=True, help_text='Sleep quality from previous night (1-10 scale)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Hours of sleep from previous night', max_digits=4, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about mood, feelings, or events', null=True)),
                ('gratitude_note', models.TextField(blank=True, help_text="Something you're grateful for today", null=True)),
                ('goals_tomorrow', models.TextField(blank=True, help_text='Goals or intentions for tomorrow', null=True)),
                ('weather_condition', models.CharField(blank=True, help_text='Weather condition (e.g., sunny, rainy, cloudy)', max_length=50, null=True)),
                ('location', models.CharField(blank=True, help_text='Location where mood was logged', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activities', models.ManyToManyField(blank=True, help_text='Activities done today that might affect mood', to='mental_wellness.activitytype')),
                ('emotions', models.ManyToManyField(blank=True, help_text='Specific emotions experienced', to='mental_wellness.emotion')),
                ('mood_category', models.ForeignKey(blank=True, help_text='Primary mood category for this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mental_wellness.moodcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Mood Entries',
                'ordering': ['-entry_date', '-entry_time'],
            },
        ),
        migrations.CreateModel(
            name='MoodInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('PATTERN', 'Pattern Recognition'), ('CORRELATION', 'Correlation Analysis'), ('TREND', 'Trend Analysis'), ('RECOMMENDATION', 'Recommendation'), ('MILESTONE', 'Milestone Achievement'), ('WARNING', 'Warning/Alert')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('confidence_score', models.DecimalField(decimal_places=2, help_text='Confidence in this insight (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('date_range_start', models.DateField()),
                ('date_range_end', models.DateField()),
                ('actionable', models.BooleanField(default=False)),
                ('action_items', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('user_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('related_entries', models.ManyToManyField(blank=True, to='mental_wellness.moodentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='MoodTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('STRESS', 'Stress & Pressure'), ('RELATIONSHIPS', 'Relationships'), ('WORK', 'Work & Career'), ('HEALTH', 'Health Issues'), ('FINANCIAL', 'Financial Concerns'), ('ENVIRONMENT', 'Environmental Factors'), ('SLEEP', 'Sleep Related'), ('HORMONAL', 'Hormonal Changes'), ('SEASONAL', 'Seasonal Changes'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('typical_impact', models.CharField(choices=[('NEGATIVE', 'Negative'), ('POSITIVE', 'Positive'), ('NEUTRAL', 'Neutral')], default='NEGATIVE', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.AddField(
            model_name='moodentry',
            name='triggers',
            field=models.ManyToManyField(blank=True, help_text='Triggers that affected mood today', to='mental_wellness.moodtrigger'),
        ),
        migrations.AlterUniqueTogether(
            name='moodentry',
            unique_together={('user', 'entry_date', 'entry_time')},
        ),
    ]
