# Generated by Django 5.2.6 on 2025-09-11 13:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(help_text='Full name of the person sending the message', max_length=150)),
                ('email', models.EmailField(help_text='Email address for response', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('subject', models.CharField(help_text='Brief description of the inquiry', max_length=200)),
                ('message', models.TextField(help_text='Detailed message content')),
                ('category', models.CharField(choices=[('GENERAL', 'General Inquiry'), ('SUPPORT', 'Technical Support'), ('BILLING', 'Billing & Pricing'), ('FEATURE', 'Feature Request'), ('BUG', 'Bug Report'), ('PARTNERSHIP', 'Partnership Inquiry'), ('MEDIA', 'Media & Press'), ('OTHER', 'Other')], default='GENERAL', help_text='Category of the message for better organization', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New Message'), ('READ', 'Message Read'), ('IN_PROGRESS', 'Response In Progress'), ('RESPONDED', 'Response Sent'), ('RESOLVED', 'Issue Resolved'), ('CLOSED', 'Closed')], default='NEW', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low Priority'), ('MEDIUM', 'Medium Priority'), ('HIGH', 'High Priority'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the sender', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device information', null=True)),
                ('referrer', models.URLField(blank=True, help_text='Page from which the contact form was submitted', null=True)),
                ('first_read_at', models.DateTimeField(blank=True, help_text='When the message was first read', null=True)),
                ('responded_at', models.DateTimeField(blank=True, help_text='When a response was sent', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for tracking and follow-up', null=True)),
                ('response_sent', models.TextField(blank=True, help_text='Copy of the response sent to the user', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Staff member assigned to handle this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contact_messages', to=settings.AUTH_USER_MODEL)),
                ('first_read_by', models.ForeignKey(blank=True, help_text='Staff member who first read the message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_read_contact_messages', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, help_text='Staff member who sent the response', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_contact_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='dashboard_c_email_198cfd_idx'), models.Index(fields=['status'], name='dashboard_c_status_8fc331_idx'), models.Index(fields=['priority'], name='dashboard_c_priorit_4c8e16_idx'), models.Index(fields=['category'], name='dashboard_c_categor_b65c33_idx'), models.Index(fields=['created_at'], name='dashboard_c_created_28689d_idx')],
            },
        ),
        migrations.CreateModel(
            name='EarlyAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(help_text='Email address for early access notifications', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('full_name', models.CharField(help_text='Full name of the person requesting access', max_length=150)),
                ('phone_number', models.CharField(blank=True, help_text='Optional phone number for priority notifications', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('primary_interest', models.CharField(choices=[('DNA_ANALYSIS', 'DNA Analysis & Genetic Insights'), ('MENTAL_WELLNESS', 'Mental Wellness & Mood Tracking'), ('NUTRITION', 'Nutrition & Dietary Planning'), ('FITNESS', 'Fitness & Health Monitoring'), ('AI_COMPANION', 'AI Health Companion'), ('COMPREHENSIVE', 'Complete Health Platform'), ('OTHER', 'Other')], help_text='Primary area of interest in the platform', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('CONTACTED', 'Initial Contact Made'), ('INTERESTED', 'Showed Interest'), ('ONBOARDED', 'Successfully Onboarded'), ('NOT_INTERESTED', 'Not Interested'), ('INVALID', 'Invalid Request')], default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low Priority'), ('MEDIUM', 'Medium Priority'), ('HIGH', 'High Priority'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('source', models.CharField(blank=True, help_text='Source of the request (e.g., website, referral, etc.)', max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the requester', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device information', null=True)),
                ('contacted_at', models.DateTimeField(blank=True, help_text='When the user was first contacted', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for tracking and follow-up', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contacted_by', models.ForeignKey(blank=True, help_text='Staff member who contacted the user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacted_early_access_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Early Access Request',
                'verbose_name_plural': 'Early Access Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='dashboard_e_email_fd4b72_idx'), models.Index(fields=['status'], name='dashboard_e_status_6949b4_idx'), models.Index(fields=['priority'], name='dashboard_e_priorit_4c2e51_idx'), models.Index(fields=['created_at'], name='dashboard_e_created_dc3ed9_idx')],
            },
        ),
    ]
