# Generated by Django 5.2.6 on 2025-09-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_companion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[('USER', 'User'), ('AI', 'Aevum')], max_length=10),
        ),
    ]
