# Generated by Django 5.2.6 on 2025-09-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_companion', '0002_alter_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[('USER', 'User'), ('AI', 'Aevum AI')], max_length=10),
        ),
    ]
