# Generated by Django 5.2.6 on 2025-09-13 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_companion', '0003_alter_message_sender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('TOPIC', 'Topic Suggestion'), ('FOLLOW_UP', 'Follow-up Question'), ('RELATED', 'Related Discussion'), ('WELLNESS_CHECK', 'Wellness Check-in')], max_length=20)),
                ('title', models.CharField(help_text='Suggested thread title', max_length=200)),
                ('description', models.TextField(help_text='Why this suggestion is relevant')),
                ('suggested_category', models.CharField(choices=[('MENTAL_HEALTH', 'Mental Health & Wellness'), ('NUTRITION', 'Nutrition & Diet')], help_text='Suggested category for the new thread', max_length=20)),
                ('suggested_first_message', models.TextField(blank=True, help_text='Optional suggested first message to start the conversation', null=True)),
                ('relevance_score', models.FloatField(default=0.5, help_text='AI-calculated relevance score (0.0 to 1.0)')),
                ('is_dismissed', models.BooleanField(default=False, help_text='User dismissed this suggestion')),
                ('is_used', models.BooleanField(default=False, help_text='User created a thread based on this suggestion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Thread Suggestion',
                'verbose_name_plural': 'Thread Suggestions',
                'ordering': ['-relevance_score', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-is_favorite', '-last_activity_at'], 'verbose_name': 'Chat Thread', 'verbose_name_plural': 'Chat Threads'},
        ),
        migrations.AddField(
            model_name='message',
            name='confidence_score',
            field=models.FloatField(blank=True, help_text='AI confidence score (0.0 to 1.0)', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_helpful',
            field=models.BooleanField(blank=True, help_text='User feedback: was this AI response helpful? (👍/👎)', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='processing_time_ms',
            field=models.PositiveIntegerField(blank=True, help_text='Time taken to generate AI response in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='token_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of tokens used for AI response', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='user_feedback',
            field=models.TextField(blank=True, help_text='Optional user comment about this message', null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='average_response_time_ms',
            field=models.FloatField(blank=True, help_text='Average AI response time in milliseconds', null=True),
        ),
        migrations.AddField(
            model_name='thread',
            name='category',
            field=models.CharField(choices=[('MENTAL_HEALTH', 'Mental Health & Wellness'), ('NUTRITION', 'Nutrition & Diet')], default='MENTAL_HEALTH', help_text='Thread category for better organization', max_length=20),
        ),
        migrations.AddField(
            model_name='thread',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Thread is archived (hidden from main list)'),
        ),
        migrations.AddField(
            model_name='thread',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='User marked this thread as favorite'),
        ),
        migrations.AddField(
            model_name='thread',
            name='last_activity_at',
            field=models.DateTimeField(auto_now=True, help_text='Last time a message was sent in this thread'),
        ),
        migrations.AddField(
            model_name='thread',
            name='total_ai_tokens_used',
            field=models.PositiveIntegerField(default=0, help_text='Total tokens used by AI in this thread'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[('USER', 'User'), ('AI', 'AI Assistant')], max_length=10),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread', 'sender'], name='ai_companio_thread__ed3c81_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread', 'created_at'], name='ai_companio_thread__cdc785_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_helpful'], name='ai_companio_is_help_8421a1_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['user', 'category'], name='ai_companio_user_id_caf014_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['user', 'is_favorite'], name='ai_companio_user_id_d111ea_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['user', 'is_archived'], name='ai_companio_user_id_23c91c_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['last_activity_at'], name='ai_companio_last_ac_91f596_idx'),
        ),
        migrations.AddField(
            model_name='threadsuggestion',
            name='based_on_thread',
            field=models.ForeignKey(blank=True, help_text='Thread that inspired this suggestion', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_suggestions', to='ai_companion.thread'),
        ),
        migrations.AddField(
            model_name='threadsuggestion',
            name='created_thread',
            field=models.ForeignKey(blank=True, help_text='Thread created from this suggestion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_from_suggestion', to='ai_companion.thread'),
        ),
        migrations.AddField(
            model_name='threadsuggestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_suggestions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='threadsuggestion',
            index=models.Index(fields=['user', 'is_dismissed', 'is_used'], name='ai_companio_user_id_4f8282_idx'),
        ),
        migrations.AddIndex(
            model_name='threadsuggestion',
            index=models.Index(fields=['relevance_score'], name='ai_companio_relevan_af8777_idx'),
        ),
        migrations.AddIndex(
            model_name='threadsuggestion',
            index=models.Index(fields=['created_at'], name='ai_companio_created_f62e13_idx'),
        ),
    ]
