# Generated by Django 5.2.6 on 2025-09-13 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_companion', '0005_alter_message_sender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_selected_for_qa',
            field=models.BooleanField(default=False, help_text='Message randomly selected for QA testing'),
        ),
        migrations.AddField(
            model_name='message',
            name='qa_feedback',
            field=models.TextField(blank=True, help_text='QA team feedback and notes', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='qa_reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When the QA review was completed', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='qa_reviewer',
            field=models.ForeignKey(blank=True, help_text='QA team member who reviewed this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_reviewed_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='qa_score',
            field=models.FloatField(blank=True, help_text='QA score (0.0 to 10.0) - quality assessment by QA team', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='qa_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('NEEDS_IMPROVEMENT', 'Needs Improvement'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], help_text='QA review status', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='qa_tags',
            field=models.CharField(blank=True, help_text="Comma-separated tags for QA categorization (e.g., 'accuracy,tone,helpfulness')", max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_selected_for_qa'], name='ai_companio_is_sele_767a6e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['qa_status'], name='ai_companio_qa_stat_b66d14_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['qa_score'], name='ai_companio_qa_scor_af0c1a_idx'),
        ),
    ]
