# Generated by Django 5.2.6 on 2025-09-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_companion', '0006_add_qa_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='original_word_count',
            field=models.PositiveIntegerField(blank=True, help_text='Word count of original AI response before summarization', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='was_summarized',
            field=models.BooleanField(default=False, help_text='Whether this response was summarized before being sent to user'),
        ),
    ]
