# Generated by Django 5.2.6 on 2025-09-22 10:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_companion', '0007_add_summarization_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('MENTAL_HEALTH', 'Mental Health Coaching'), ('NUTRITION', 'Nutrition Guidance'), ('FITNESS', 'Fitness Tracking'), ('THERAPY', 'Personal Therapy'), ('GENERAL', 'General Conversation')], max_length=20)),
                ('steps_config', models.JSONField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('MENTAL_HEALTH', 'Mental Health Coaching'), ('NUTRITION', 'Nutrition Guidance'), ('FITNESS', 'Fitness Tracking'), ('THERAPY', 'Personal Therapy'), ('GENERAL', 'General Conversation')], default='GENERAL', max_length=20)),
                ('state', models.CharField(choices=[('INITIALIZED', 'Workflow Started'), ('IN_PROGRESS', 'Ongoing Interaction'), ('NEEDS_REVIEW', 'Requires Human Review'), ('COMPLETED', 'Workflow Finished'), ('PAUSED', 'Temporarily Suspended')], default='INITIALIZED', max_length=20)),
                ('context', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_step', models.IntegerField(default=0)),
                ('total_steps', models.IntegerField(default=0)),
                ('insights', models.JSONField(default=dict)),
                ('thread', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to='ai_companion.thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('user_input', models.TextField()),
                ('ai_response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('relevance_score', models.FloatField(blank=True, null=True)),
                ('feedback', models.JSONField(default=dict)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='ai_companion.workflow')),
            ],
        ),
    ]
