# Generated by Django 5.2.6 on 2025-09-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_companion', '0008_workflowtemplate_workflow_workflowstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='summary',
            field=models.TextField(blank=True, help_text='Concise summary of the AI response', null=True),
        ),
    ]
